config/routes.rb
Rails.application.routes.draw do
  
  resources :posts do
    resources :comments
  end
  devise_for :users
  root to: "welcome#index"

  get '/myposts', to: 'posts#show_myposts'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  broadcasts_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true
	validates :title, length: { in: 0..200 }
	validates :content, length: { in: 0..10000 }
	has_rich_text :content 
	belongs_to :user
	has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!, :except => [:index, :show]
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_post

	def create
		@post.comments.create! params.required(:comment).permit(:content)
		respond_to @post
	end

	private
	
	def set_post
		@post = Post.find(params[:post_id])
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :correct_user, only: %i[ edit update destroy ]


  # GET /posts or /posts.json
  def index
    @posts = Post.all
    @users = User.all

  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  def show_myposts
    @posts = current_user.posts
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to posts_path, alert: "Not Authorized To Edit This Post" if @post.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>">
  <p>--<%= comment.content %></p>
  <p class="text-end"><%= time_tag comment.created_at, "data-local": "time-ago" %></p>
</div>

app/views/comments/_new.html.erb
<%= form_with model: [ post, Comment.new ] do |form|%>
	Your comment:<br>
	<%= form.text_area :content, size: "60x2"%><br>
	<%= form.submit%>
<% end %>
<br>
<br>

app/views/layouts/_messages.html.erb
<% if notice %>
      <div class='alert alert-success'>
            <%= notice %>
      </div>
<% end %>
<% if alert %>
      <div class='alert alert-danger'>
            <%= alert %>
      </div>
<% end %>

app/views/layouts/_navgation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
          <% if user_signed_in? %>
            <li class="nav-item">
               <%= link_to 'Posts', posts_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
               <%= link_to 'My posts', myposts_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
               <%= link_to 'New post', new_post_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Profile', edit_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign out", destroy_user_session_path,class: 'nav-link', data: { turbo_method: :delete } %>
            </li>
          <% else %>
            <li class="nav-item">
               <%= link_to 'Posts', posts_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
               <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
               <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostsDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/navgation' %>
      <div class = "row">
        <div class="col">

        </div>
        <div class="col-6">
          <div class="container">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <div class="col">

        </div>
      </div>
  </body>
</html>

app/views/posts/_comments.html.erb
<h2>Comments</h2>

<div id="comments">
	<%= render post.comments %>
</div>

<%= render "comments/new",post: post %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title ,size:60 %>
  </div>

  <div >
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content, size: "60x4" %>
  </div>

   <div>
    <%= form.number_field :user_id, id: :post_user_id, value: current_user.id, type: :hidden %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="card" style="width: 20rem;">
  <div class="card-body">
    <h5 class="card-title"><%= post.title %></h5>
      <p class="card-text"><%= post.content %></p>
      <p>
      Posted <%= time_tag post.created_at, "data-local": "time-ago" %>
      </p>
      <p>
      <strong><%= pluralize post.comments.count, "comment"%></strong>
      </p>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show", @post,class:"btn btn-outline-secondary" %>
  <%= link_to "Back", posts_path, class:"btn btn-outline-secondary" %>
</div>

app/views/posts/index.html.erb
<h1>Posts</h1>
<div id="posts">
	<% @posts.each do |post| %>
		<div id="<%= dom_id post %>" class="card" style="width: 42rem;">
			<div class="card-body">
				<h3  class="card-title"><%= post.title %></h3>
					<% @users.each do |user| %>
						<% if user.id == post.user_id %>
							<i>
								Posted by: <%= user.email %>
							</i>	
						<% end %>
					<% end %>
					<p class="card-text"><%= post.content %></p>
					<p>
						<i><%= pluralize post.comments.count, "comment"%></i>
					</p>
					<%= link_to "show",  post,  class:"btn btn-outline-secondary" %>
			</div>
		</div>
		<br>
	<% end %>
</div>
<br>
<br>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path ,class:"btn btn-outline-secondary" %>
</div>

app/views/posts/show.html.erb
<%= turbo_stream_from @post %>
<p style="color: green"><%= notice %></p>
<h1>Post</h1>
  <h2 class="text-center"><%= @post.title %></h2>
  <h4 class="text-start"><%= @post.content %></h4>
  <p class="text-end">Posted <%= time_tag @post.created_at, "data-local": "time-ago" %></p>
<br>
<br>
<div class="btn-group" role="group">
  <%= link_to "Edit", edit_post_path(@post), class:"btn btn-outline-secondary" %>
  <%= link_to "Back", posts_path, class:"btn btn-outline-secondary" %>
  <%= button_to "Delete", @post, method: :delete, class:"btn btn-outline-secondary" %>
</div>
<br>
<br>
<%= render "posts/comments", post: @post  %>

app/views/posts/show_myposts.html.erb
<h1>My Posts</h1>
<div id="posts">
  <% @posts.each do |post| %>
    <div id="<%= dom_id post %>" class="card" style="width: 42rem;">
      <div class="card-body">
        <h3  class="card-title"><%= post.title %></h3>
          <i>
            Posted <%= time_tag post.created_at, "data-local": "time-ago" %>
          </i>
          <p class="card-text"><%= post.content %></p>
          <p>
            <i><%= pluralize post.comments.count, "comment"%></i>
          </p>
          <%= link_to "show",  post,  class:"btn btn-outline-secondary" %>
      </div>
    </div>
    <br>
  <% end %>
</div>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
	<br>
	<br>
	<h1>You have logged in successfully and can now create entries.</h1>
<% else %>
	<br>
	<br>
	<h1>I am Hacker Websites :) </h1>
	<h4>A collection of all the really cool websites where you can browse or create your own entries on that you find really cool.</h4>
<%end%>